name: Node.js CI
on:
  pull_request:
    branches:
      - develop
strategy:
  matrix:
    node-version:: ["16", "18"]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: npm install
      - run: npm test
